global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'validator'
    static_configs:
      - targets: ['validator:9090']
        labels:
          service: 'chulobots-validator'
